### ISSUE TITLE
[Bug]: Sponges eat light sources from other mods

### ISSUE THREAD

**Issue by ApolloX939** [BenjieFiftysix/soggy-sponge#2]
While the simple eating all airlike nodes might seem like a great idea, it's not... it breaks horribly when mods like [Technic](https://content.minetest.net/packages/RealBadAngel/technic/) and it's [flashlight](https://github.com/minetest-mods/technic/blob/master/technic/tools/flashlight.lua) and [Good Torch](https://content.minetest.net/packages/LissoBone/goodtorch/) are all in the same area as a sponge.

A simple fix:

```lua
-- added to init.lua in the beginning
sponge = {
  include_lava = false,
}
sponge.liquids = {
  "default:water_source",
  "default:water_flowing",
  "default:river_water_source",
  "default:river_water_flowing"
}
if sponge.include_lava then
  -- Makes the sponge soak up lava too? (deems too powerful, but handy if one wants/needs to do that)
  table.insert(sponge.liquids, "default:lava_source")
  table.insert(sponge.liquids, "default:lava_flowing")
end
-- a util function to check our liquids for if a node is within it
local can_replace = function(node)
  if type(node) ~= "string" and node.name ~= nil then
    -- In case we were given a node not a node.name
    node = node.name
  end
  for idx, val in pairs(sponge.liquids) do
    if val[1] == node then
      return true
    end
  end
  return false
end

-- now to update construct function (after_place_node)
local construct = function(pos, placer, itemstack, pointed_thing)
    local playername = placer:get_player_name()

    if not minetest.is_protected(pos, playername) then
        local count = 0

        for x = pos.x-area, pos.x+area do
            for y = pos.y-area, pos.y+area do
                for z = pos.z-area, pos.z+area do

                    local n = minetest.get_node({x=x, y=y, z=z}).name
                    local def = minetest.registered_nodes[n]
                    if def ~= nil and (n == "air" or def["drawtype"] == "liquid" or def["drawtype"] == "flowingliquid") then
                        local p = {x=x, y=y, z=z}
                        if not minetest.is_protected(p, playername) and can_replace(n) then
                            if n ~= "air" then
                                count = count + 1  -- counting liquids
                            end
                            minetest.set_node(p, {name=modname..":liquid_stop"})
                        end
                    end
                end
            end
        end

        if count > keep_dry then  -- turns soggy if it removed more than `keep_dry` nodes
            minetest.swap_node(pos, {name=modname..":soggy_sponge", param1=1})
        end
    end
end
```

Some things to note: (Mostly for myself)
- [x] I have not tested the above code to verify it works exactly as expected/expecting.

**Comment by ApolloX939** [comment]
Ok, I think I've figured it out, both mods see the liquid_stop node and thus stop themselves too.

I can manually patch both of these on my server, but both mods will need to update to support this mod's "feature", perhaps it would be best if we could change to a different method of blocking liquid nodes, but not blocking these mods, they are quite useful. (I've encountered underwater caverns which sponges are needed to soak up lots of water)

**Comment by Benjie56** [comment]
The issue is that the torch mods need somewhere to place a light node, which they have implemented for air and water, and not for `sponge:liquid_stop`. There is not much that can be done about this, unless those mods specifically add support for this sponge mod.

Your suggested code reduces this issue by not converting `air` to `liquid_stop` nodes, however the issue would still occur in positions that were originally water. The reason I have not done it like this is because when removing water flowing it would often result in water floating 1 node above the ground, where it had originally flowed, which would look very unusual.
Your code also adds a whitelist of liquid nodes, with optional lava removal.

I have implemented both of these features as configurable options in [a3ae658](https://github.com/BenjieFiftysix/sponge/commit/a3ae65833f2134226676e6757b23efd083638377).
The option to keep air nodes needs to be set as `sponge_replace_air_nodes = false` in minetest.conf, or set `settings > All settings > Content: Mods > Sponge > Replace air nodes` to `false`.
A whitelist/blacklist of groups can also be set, as per the updated readme.

**Comment by Benjie56** [comment]
Sorry, I didn't see your fork. I'll have a look at that as well, it looks like you have some very interesting features.
